export default function Page() {
  return (
    <main className="nb-container py-16 nb-stack">
      <h1 className="text-5xl font-bold tracking-tight">newBrush + Next.js</h1>
      <p className="text-lg text-muted max-w-prose">
        Utilities are generated by @newbrush/postcss from the classes in app/.
      </p>
      <div className="grid gap-6 md:grid-cols-3">
        {["Tokens", "Utilities", "Components"].map((title) => (
          <article key={title} className="nb-card p-6 hover:shadow-lg transition">
            <h2 className="nb-card__title">{title}</h2>
          </article>
        ))}
      </div>
    </main>
  );
}
