/**
 * Builds @newbrush/tokens (specs/001-core-framework tasks T012).
 * Style Dictionary v4 parses the DTCG sources, resolves aliases and applies value transforms;
 * the outputs below are written from its transformed token list.
 */
import { mkdir, rm, writeFile } from "node:fs/promises";
import { ResolvedToken, type Theme } from "@newbrush/schema";
import StyleDictionary from "style-dictionary";
import type { TransformedToken } from "style-dictionary/types";
import { aliasPath, cssVarName } from "./lib/names.ts";

const THEMES: Theme[] = [
  { name: "light", colorScheme: "light", overrides: {} },
  { name: "dark", colorScheme: "dark", overrides: {} },
  { name: "contrast", colorScheme: "light", extends: "light", overrides: {} },
];
const HEADER = "/* newBrush design tokens — generated by @newbrush/tokens, do not edit. */\n";

StyleDictionary.registerTransform({
  name: "nb/name",
  type: "name",
  transform: (token) => cssVarName(token.path).slice(2),
});

const sd = new StyleDictionary({
  source: ["src/**/*.json"],
  usesDtcg: true,
  log: { verbosity: "silent", warnings: "error" },
  platforms: {
    css: { transforms: ["nb/name", "fontFamily/css", "cubicBezier/css", "shadow/css/shorthand"] },
  },
});
const { allTokens } = await sd.getPlatformTokens("css");

const byName = new Map(allTokens.map((t) => [t.path.join("."), t]));
const tierOf = (t: TransformedToken) =>
  /src\/(primitive|semantic|component)\//.exec(t.filePath)?.[1] as ResolvedToken["tier"];
const themeAliases = (t: TransformedToken): Record<string, string> =>
  (t.original.$extensions as { "nb.themes"?: Record<string, string> } | undefined)?.["nb.themes"] ??
  {};

/** CSS value: references stay live as var() so themes and runtime overrides cascade; others are transformed values. */
function cssValue(raw: unknown, resolved: unknown): string {
  const alias = aliasPath(raw);
  if (alias) {
    if (!byName.has(alias.join("."))) throw new Error(`Unknown alias {${alias.join(".")}}`);
    return `var(${cssVarName(alias)})`;
  }
  return String(resolved);
}

function resolvedThemeValue(alias: string): string {
  const path = aliasPath(alias);
  const target = path && byName.get(path.join("."));
  if (!target) throw new Error(`Unknown theme alias ${alias}`);
  return String(target.$value);
}

const decl = (t: TransformedToken, value: string) => `    --${t.name}: ${value};`;
const block = (selector: string, lines: string[]) => `  ${selector} {\n${lines.join("\n")}\n  }`;
const themed = (name: string) =>
  allTokens
    .filter((t) => themeAliases(t)[name])
    .map((t) => decl(t, cssValue(themeAliases(t)[name], "")));
const marker = (scheme: string, extra: string[] = []) => [
  `    color-scheme: ${scheme};`,
  `    --nb-scheme: ${scheme};`,
  ...extra,
];

const primitives = allTokens
  .filter((t) => tierOf(t) === "primitive")
  .map((t) => decl(t, cssValue(t.original.$value, t.$value)));
const base = allTokens
  .filter((t) => tierOf(t) !== "primitive")
  .map((t) => decl(t, cssValue(t.original.$value, t.$value)));
const dark = [...marker("dark"), ...themed("dark")];
const contrast = ["    --nb-contrast: more;", ...themed("contrast")];
const indent = (s: string) => s.replace(/^/gm, "  ");

const blocks = {
  primitives: block(":root", primitives),
  light: block(':root,\n  [data-nb-theme="light"],\n  [data-nb-theme="contrast"]', [
    ...marker("light"),
    ...base,
  ]),
  dark: [
    block('[data-nb-theme="dark"]', dark),
    `  @media (prefers-color-scheme: dark) {\n${indent(block(":root:not([data-nb-theme])", dark))}\n  }`,
  ].join("\n\n"),
  contrast: [
    block('[data-nb-theme="contrast"]', contrast),
    `  @media (prefers-contrast: more) and (prefers-color-scheme: light) {\n${indent(block(":root:not([data-nb-theme])", contrast))}\n  }`,
  ].join("\n\n"),
};
const layer = (...parts: string[]) => `${HEADER}@layer nb.tokens {\n${parts.join("\n\n")}\n}\n`;

// ── Manifest-shaped JSON ────────────────────────────────────────────────────
const resolved = allTokens.map((t) => {
  const themes: Record<string, string> = {};
  for (const [name, alias] of Object.entries(themeAliases(t)))
    themes[name] = resolvedThemeValue(alias);
  const ref = aliasPath(t.original.$value);
  return ResolvedToken.parse({
    path: t.path,
    name: t.path.join("."),
    cssVar: `--${t.name}`,
    tier: tierOf(t),
    type: t.$type,
    value: String(t.$value),
    themes,
    references: ref ? [ref.join(".")] : [],
    description: t.$description ?? (t.original.$description as string | undefined),
  });
});

// ── Figma Variables (one collection, a mode per theme) ──────────────────────
const figmaType = (type: string) =>
  type === "color" ? "COLOR" : type === "number" || type === "fontWeight" ? "FLOAT" : "STRING";
const figma = {
  $schema: "https://newbrush.dev/schema/figma-variables.v1.json",
  collections: [
    {
      name: "newBrush",
      modes: THEMES.map((t) => t.name),
      variables: resolved.map((t) => ({
        name: t.path.join("/"),
        type: figmaType(t.type),
        description: t.description ?? "",
        valuesByMode: Object.fromEntries(THEMES.map((m) => [m.name, t.themes[m.name] ?? t.value])),
      })),
    },
  ],
};

// ── JS / TS ─────────────────────────────────────────────────────────────────
const names = resolved.map((t) => t.name);
const js = `${HEADER.replace("/*", "//").replace(" */", "")}export const tokens = ${JSON.stringify(
  Object.fromEntries(
    resolved.map((t) => [t.name, { cssVar: t.cssVar, value: t.value, themes: t.themes }]),
  ),
  null,
  2,
)};\n\nexport const themes = ${JSON.stringify(THEMES, null, 2)};\n\n/** \`var(--nb-…)\` reference for a token name. */\nexport function cssVar(name) {\n  const token = tokens[name];\n  if (!token) throw new Error(\`Unknown newBrush token "\${name}"\`);\n  return \`var(\${token.cssVar})\`;\n}\n`;
const dts = `export type TokenName =\n${names.map((n) => `  | ${JSON.stringify(n)}`).join("\n")};\n\nexport interface TokenEntry {\n  cssVar: \`--nb-\${string}\`;\n  value: string;\n  themes: Partial<Record<"dark" | "contrast", string>>;\n}\n\nexport declare const tokens: Record<TokenName, TokenEntry>;\nexport declare const themes: Array<{ name: string; colorScheme: "light" | "dark"; extends?: string; overrides: Record<string, string> }>;\nexport declare function cssVar(name: TokenName): \`var(--nb-\${string})\`;\n`;

// ── Write ───────────────────────────────────────────────────────────────────
await rm("dist", { recursive: true, force: true });
await mkdir("dist/css/themes", { recursive: true });
const files: Record<string, string> = {
  "dist/css/tokens.css": layer(blocks.primitives, blocks.light, blocks.dark, blocks.contrast),
  "dist/css/primitives.css": layer(blocks.primitives),
  "dist/css/themes/light.css": layer(blocks.light),
  "dist/css/themes/dark.css": layer(blocks.dark),
  "dist/css/themes/contrast.css": layer(blocks.contrast),
  "dist/tokens.json": `${JSON.stringify({ themes: THEMES, tokens: resolved }, null, 2)}\n`,
  "dist/figma-variables.json": `${JSON.stringify(figma, null, 2)}\n`,
  "dist/tokens.js": js,
  "dist/tokens.d.ts": dts,
};
for (const [file, content] of Object.entries(files)) await writeFile(file, content);
console.log(`tokens: ${resolved.length} tokens, ${Object.keys(files).length} files`);
