/**
 * Builds the `newbrush` package (specs/001-core-framework T014, T034).
 * Lightning CSS bundles @imports, lowers syntax for .browserslistrc and minifies;
 * component metadata (*.meta.ts) is validated and written to dist/manifest.json.
 */
import { readFileSync } from "node:fs";
import { copyFile, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createEngine } from "@newbrush/engine";
import { Component, LAYERS, Manifest } from "@newbrush/schema";
import browserslist from "browserslist";
import { browserslistToTargets, bundleAsync } from "lightningcss";
import { presetClasses } from "./preset.ts";

const root = new URL("../", import.meta.url);
const path = (rel: string) => fileURLToPath(new URL(rel, root));
const pkg = JSON.parse(await readFile(path("package.json"), "utf8")) as { version: string };
const targets = browserslistToTargets(browserslist(undefined, { path: path(".") }));
const layerOrder = `@layer ${LAYERS.join(", ")};`;
const banner = `/*! newBrush v${pkg.version} | MIT License | https://github.com/newsignlabs/css-project */\n`;

// The utility preset is generated by @newbrush/engine and spliced in when the bundler reads its placeholder file.
const presetEngine = createEngine({ content: ["**/*"], themeVariants: "selector" });
const preset = presetClasses(presetEngine);
const presetCss = presetEngine.generate(preset).css;
const PRESET_FILE = path("src/utilities/preset.css");

const resolver = {
  read(file: string) {
    return file === PRESET_FILE ? presetCss : readFileSync(file, "utf8");
  },
  resolve(specifier: string, from: string) {
    if (specifier.startsWith(".") || specifier.startsWith("/"))
      return fileURLToPath(new URL(specifier, pathToFileURL(from)));
    return fileURLToPath(import.meta.resolve(specifier));
  },
};

async function bundle(entry: string, outName: string): Promise<void> {
  const filename = path(entry);
  for (const minify of [false, true]) {
    const out = minify ? outName.replace(/\.css$/, ".min.css") : outName;
    const { code, map } = await bundleAsync({
      filename,
      minify,
      targets,
      resolver,
      sourceMap: minify,
      projectRoot: path("."),
    });
    const mapRef = map ? `\n/*# sourceMappingURL=${out.split("/").pop()}.map */\n` : "";
    // Lightning CSS may split the layer-order statement; restate it in full so every file declares the whole cascade.
    await writeFile(
      path(`dist/${out}`),
      banner + layerOrder + (minify ? "" : "\n") + code.toString() + mapRef,
    );
    if (map) await writeFile(path(`dist/${out}.map`), map);
  }
}

async function componentNames(): Promise<string[]> {
  const entries = await readdir(path("src/components"), { withFileTypes: true });
  return entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();
}

async function importMeta(file: string): Promise<unknown[]> {
  const mod = (await import(pathToFileURL(path(file)).href)) as { default: unknown };
  return Array.isArray(mod.default) ? mod.default : [mod.default];
}

/** Layout primitives (src/layout/index.meta.ts) + one meta per component folder (T023). */
async function loadComponents(names: string[]): Promise<Component[]> {
  const entries: [string, unknown][] = (await importMeta("src/layout/index.meta.ts")).map((m) => [
    "layout",
    m,
  ]);
  for (const name of names) {
    for (const meta of await importMeta(`src/components/${name}/${name}.meta.ts`))
      entries.push([name, meta]);
  }
  const components: Component[] = [];
  for (const [source, meta] of entries) {
    const parsed = Component.safeParse(meta);
    if (!parsed.success) throw new Error(`Invalid meta in "${source}":\n${parsed.error.message}`);
    if (components.some((c) => c.name === parsed.data.name))
      throw new Error(`Duplicate component "${parsed.data.name}"`);
    components.push(parsed.data);
  }
  return components;
}

await rm(path("dist"), { recursive: true, force: true });
await mkdir(path("dist/components"), { recursive: true });
await mkdir(path("dist/themes"), { recursive: true });

await bundle("src/core.css", "newbrush-core.css");
await bundle("src/index.css", "newbrush.css");
await bundle("src/full.css", "newbrush-full.css");

const names = await componentNames();
for (const name of names)
  await bundle(`src/components/${name}/${name}.css`, `components/${name}.css`);

for (const theme of ["light", "dark", "contrast"]) {
  await copyFile(
    fileURLToPath(import.meta.resolve(`@newbrush/tokens/css/themes/${theme}.css`)),
    path(`dist/themes/${theme}.css`),
  );
}

const utilityEngine = createEngine({ content: ["**/*"] });
const tokens = JSON.parse(
  await readFile(fileURLToPath(import.meta.resolve("@newbrush/tokens/tokens.json")), "utf8"),
);
const manifest = Manifest.parse({
  name: "newbrush",
  version: pkg.version,
  schemaVersion: 1,
  layers: [...LAYERS],
  tokens: tokens.tokens,
  themes: tokens.themes,
  variants: utilityEngine.variants(),
  utilities: utilityEngine.utilityFamilies(),
  components: await loadComponents(names),
});
await writeFile(path("dist/manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
// ── Editor support (T058): TypeScript class-name types and VS Code custom data ─────────────────────────────
const componentClasses = [
  ...new Set(
    manifest.components.flatMap((c) => [
      c.className,
      ...c.anatomy.map((a) => a.className),
      ...c.modifiers.map((m) => m.className),
    ]),
  ),
]
  .filter((c) => /^nb-[a-z0-9_-]+$/.test(c))
  .sort();
const utilities = presetEngine.knownClasses();
const variantNames = manifest.variants.map((v) => v.name).filter((n) => /^[@a-z0-9-]+$/.test(n));
const union = (items: string[]) =>
  items.length ? items.map((i) => `  | ${JSON.stringify(i)}`).join("\n") : "  never";
await writeFile(
  path("dist/classes.d.ts"),
  `/* newBrush class names — generated by the newbrush build. */\nexport type NewBrushComponentClass =\n${union(componentClasses)};\n\n` +
    `export type NewBrushUtility =\n${union(utilities)};\n\nexport type NewBrushVariant =\n${union(variantNames)};\n\n` +
    "/** Any newBrush class: components, utilities and variant-prefixed utilities (arbitrary values are not enumerated). */\n" +
    "export type NewBrushClass = NewBrushComponentClass | NewBrushUtility | `${string}:${NewBrushUtility}`;\n",
);
const describe = (cls: string) => manifest.components.find((c) => c.className === cls)?.description;
await writeFile(
  path("dist/vscode.css-data.json"),
  `${JSON.stringify(
    {
      version: 1.1,
      atDirectives: [
        {
          name: "@nb-apply",
          description:
            "Inline newBrush utilities into the current rule, e.g. `@nb-apply p-6 rounded-xl hover:shadow-lg;`",
        },
        {
          name: "@newbrush",
          description:
            "`@newbrush utilities;` is replaced with the utilities used in your content files.",
        },
      ],
    },
    null,
    2,
  )}\n`,
);
await writeFile(
  path("dist/vscode.html-data.json"),
  `${JSON.stringify(
    {
      version: 1.1,
      globalAttributes: [
        {
          name: "class",
          description: "newBrush components and utilities",
          values: [
            ...componentClasses.map((name) => ({
              name,
              ...(describe(name) ? { description: describe(name) } : {}),
            })),
            ...utilities.map((name) => ({ name })),
          ],
        },
      ],
    },
    null,
    2,
  )}\n`,
);

console.log(
  `newbrush: built ${3 + names.length} bundles, ${manifest.components.length} components, ${manifest.tokens.length} tokens, ${preset.length} preset utilities`,
);
