import type { Family } from "../types.ts";
import { keywords, range, scaleFamily, staticFamily } from "./helpers.ts";

const alignments = {
  start: "start",
  end: "end",
  center: "center",
  stretch: "stretch",
  baseline: "baseline",
};
const distribution = {
  start: "flex-start",
  end: "flex-end",
  center: "center",
  between: "space-between",
  around: "space-around",
  evenly: "space-evenly",
  stretch: "stretch",
  normal: "normal",
};
const spans = Object.fromEntries(range(1, 12).map((n) => [n, `span ${n} / span ${n}`]));
const lines = Object.fromEntries(range(1, 13).map((n) => [n, n]));

// T044 — flexbox and grid.
export const flexgrid: Family[] = [
  staticFamily("flex-direction", "layout", "Flex direction and wrapping", {
    ...keywords("flex", "flex-direction", {
      row: "row",
      "row-reverse": "row-reverse",
      col: "column",
      "col-reverse": "column-reverse",
    }),
    ...keywords("flex", "flex-wrap", {
      wrap: "wrap",
      "wrap-reverse": "wrap-reverse",
      nowrap: "nowrap",
    }),
  }),
  staticFamily("flex", "layout", "Flex shorthand", {
    ...keywords("flex", "flex", {
      "1": "1 1 0%",
      auto: "1 1 auto",
      initial: "0 1 auto",
      none: "none",
    }),
    grow: [["flex-grow", "1"]],
    "grow-0": [["flex-grow", "0"]],
    shrink: [["flex-shrink", "1"]],
    "shrink-0": [["flex-shrink", "0"]],
  }),
  scaleFamily({
    name: "flex-basis",
    category: "layout",
    description: "Initial main size of a flex item",
    roots: ["basis"],
    properties: ["flex-basis"],
    scale: (t) => t.space,
    tokenGroup: "space",
    extra: { auto: "auto", full: "100%" },
    fractions: true,
  }),
  scaleFamily({
    name: "order",
    category: "layout",
    description: "Order of flex and grid items",
    roots: ["order"],
    properties: ["order"],
    extra: {
      first: "-9999",
      last: "9999",
      none: "0",
      ...Object.fromEntries(range(1, 12).map((n) => [n, n])),
    },
    arbitrary: "number",
    negative: true,
  }),
  scaleFamily({
    name: "grid-template-columns",
    category: "layout",
    description: "Grid columns: n equal tracks or an arbitrary template",
    roots: ["grid-cols"],
    properties: ["grid-template-columns"],
    extra: {
      none: "none",
      subgrid: "subgrid",
      ...Object.fromEntries(range(1, 12).map((n) => [n, `repeat(${n}, minmax(0, 1fr))`])),
    },
    arbitrary: "grid-template",
  }),
  scaleFamily({
    name: "grid-template-rows",
    category: "layout",
    description: "Grid rows",
    roots: ["grid-rows"],
    properties: ["grid-template-rows"],
    extra: {
      none: "none",
      subgrid: "subgrid",
      ...Object.fromEntries(range(1, 12).map((n) => [n, `repeat(${n}, minmax(0, 1fr))`])),
    },
    arbitrary: "grid-template",
  }),
  staticFamily("grid-span-keywords", "layout", "Full-width and automatic grid placement", {
    "col-auto": [["grid-column", "auto"]],
    "col-span-full": [["grid-column", "1 / -1"]],
    "row-auto": [["grid-row", "auto"]],
    "row-span-full": [["grid-row", "1 / -1"]],
  }),
  scaleFamily({
    name: "grid-column-span",
    category: "layout",
    description: "Columns spanned by a grid item",
    roots: ["col-span"],
    properties: ["grid-column"],
    extra: spans,
    arbitrary: "number",
  }),
  scaleFamily({
    name: "grid-column-start",
    category: "layout",
    description: "Grid column start line",
    roots: ["col-start"],
    properties: ["grid-column-start"],
    extra: { auto: "auto", ...lines },
    arbitrary: "number",
  }),
  scaleFamily({
    name: "grid-column-end",
    category: "layout",
    description: "Grid column end line",
    roots: ["col-end"],
    properties: ["grid-column-end"],
    extra: { auto: "auto", ...lines },
    arbitrary: "number",
  }),
  scaleFamily({
    name: "grid-row-span",
    category: "layout",
    description: "Rows spanned by a grid item",
    roots: ["row-span"],
    properties: ["grid-row"],
    extra: spans,
    arbitrary: "number",
  }),
  scaleFamily({
    name: "grid-row-start",
    category: "layout",
    description: "Grid row start line",
    roots: ["row-start"],
    properties: ["grid-row-start"],
    extra: { auto: "auto", ...lines },
    arbitrary: "number",
  }),
  scaleFamily({
    name: "grid-row-end",
    category: "layout",
    description: "Grid row end line",
    roots: ["row-end"],
    properties: ["grid-row-end"],
    extra: { auto: "auto", ...lines },
    arbitrary: "number",
  }),
  staticFamily("grid-auto", "layout", "Implicit grid tracks and auto-placement", {
    ...keywords("grid-flow", "grid-auto-flow", {
      row: "row",
      col: "column",
      dense: "dense",
      "row-dense": "row dense",
      "col-dense": "column dense",
    }),
    ...keywords("auto-cols", "grid-auto-columns", {
      auto: "auto",
      min: "min-content",
      max: "max-content",
      fr: "minmax(0, 1fr)",
    }),
    ...keywords("auto-rows", "grid-auto-rows", {
      auto: "auto",
      min: "min-content",
      max: "max-content",
      fr: "minmax(0, 1fr)",
    }),
  }),
  scaleFamily({
    name: "gap",
    category: "spacing",
    description: "Gap between grid/flex items",
    roots: ["gap"],
    properties: ["gap"],
    scale: (t) => t.space,
    tokenGroup: "space",
    extra: { px: "1px" },
  }),
  scaleFamily({
    name: "column-gap",
    category: "spacing",
    description: "Inline-axis gap",
    roots: ["gap-x"],
    properties: ["column-gap"],
    scale: (t) => t.space,
    tokenGroup: "space",
    extra: { px: "1px" },
  }),
  scaleFamily({
    name: "row-gap",
    category: "spacing",
    description: "Block-axis gap",
    roots: ["gap-y"],
    properties: ["row-gap"],
    scale: (t) => t.space,
    tokenGroup: "space",
    extra: { px: "1px" },
  }),
  staticFamily("alignment", "layout", "Box alignment for flex and grid", {
    ...keywords("justify", "justify-content", distribution),
    ...keywords("justify-items", "justify-items", alignments),
    ...keywords("justify-self", "justify-self", { auto: "auto", ...alignments }),
    ...keywords("content", "align-content", distribution),
    ...keywords("items", "align-items", { ...alignments, start: "flex-start", end: "flex-end" }),
    ...keywords("self", "align-self", {
      auto: "auto",
      ...alignments,
      start: "flex-start",
      end: "flex-end",
    }),
    ...keywords("place-content", "place-content", {
      ...alignments,
      between: "space-between",
      around: "space-around",
      evenly: "space-evenly",
    }),
    ...keywords("place-items", "place-items", alignments),
    ...keywords("place-self", "place-self", { auto: "auto", ...alignments }),
  }),
];
